services:
  kafka-producer:
    build:
      context: ./kafka-producer-main/kafka-producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092

  kafka-consumer:
    build:
      context: ./kafka-consumer-main/kafka-consumer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092

networks:
  default:
    external: true
    name: dbe3_exp3_s1_backend-main_default
