services:
  config-server:
    build:
      context: ./dbe3_exp3_s1_config-server-main
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native

  eureka-server:
    build:
      context: ./dbe3_exp3_s1_eureka-server-main
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - CONFIG_SERVER_URL=http://config-server:8888

  api-gateway:
    build:
      context: ./dbe3_exp3_s1_api-getaway-main
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  backend-service:
    build:
      context: ./dbe3_exp3_s1_backend-main
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    volumes:
      - ./dbe3_exp3_s1_backend-main/Wallet_dbe3db:/app/Wallet_dbe3db:ro

  kafka-producer:
    build:
      context: ./kafka-producer-main/kafka-producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    external_links:
      - dbe3-microservicios-kafka-proyecto-kafka-1-1:kafka-1
      - dbe3-microservicios-kafka-proyecto-kafka-2-1:kafka-2

  kafka-consumer:
    build:
      context: ./kafka-consumer-main/kafka-consumer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    external_links:
      - dbe3-microservicios-kafka-proyecto-kafka-1-1:kafka-1
      - dbe3-microservicios-kafka-proyecto-kafka-2-1:kafka-2
