services:
  kafka-producer:
    build:
      context: ./kafka-producer-main/kafka-producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    external_links:
      - dbe3-microservicios-kafka-proyecto-kafka-1-1:kafka-1
      - dbe3-microservicios-kafka-proyecto-kafka-2-1:kafka-2

  kafka-consumer:
    build:
      context: ./kafka-consumer-main/kafka-consumer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    external_links:
      - dbe3-microservicios-kafka-proyecto-kafka-1-1:kafka-1
      - dbe3-microservicios-kafka-proyecto-kafka-2-1:kafka-2
