spring:
  cloud:
    gateway:
      routes:
        - id: backend-transactions
          uri: lb://backend-service
          predicates:
            - Path=/api/transactions
          filters:
            - SetPath=/backend/api/transaction
        - id: backend-accounts
          uri: lb://backend-service
          predicates:
            - Path=/api/accounts
          filters:
            - SetPath=/backend/api/annual-account
        - id: backend-interests
          uri: lb://backend-service
          predicates:
            - Path=/api/interests
          filters:
            - SetPath=/backend/api/interest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[reactor.netty]': INFO

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      backend-circuit-breaker:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
    instances:
      backend-circuit-breaker:
        base-config: default